### ISSUE TITLE
Update backend config and dependencies to use MongoDB

### ISSUE THREAD

**Issue by JasonFreeberg** [data-science-ucsb/gauchocourses#25]
Related to #7 

The backend of the application is currently configured to use PostgreSQL, but to make this application as cost-effective as possible for the club we want to use Azure's free tier of Cosmos DB. This will require some updates to the backend to make it compatible with Cosmos.

Before working on this, see this to learn more about Spring Data Repositories: https://docs.spring.io/spring-data/data-commons/docs/2.2.1.RELEASE/reference/html/#repositories

This isn't an exhaustive To-Do list, but it will give an idea of where to start:
- [x] Replace "[JpaRepository](https://github.com/data-science-ucsb/gauchocourses/blob/main/backend/src/main/java/org/gaucho/courses/repository/ScheduleRepository.java)" with "MongoRepository"
- [x] Remove the H2 dependency and any configuration related to it, replace with FlapDoodle's embedded mongo: https://docs.spring.io/spring-boot/docs/1.4.x/reference/html/boot-features-nosql.html#boot-features-mongo-embedded. (H2 is an in-memory database that's started when you run the app locally for development. Since we're switching to Mongo however, H2 will not work for us anymore because H2 is a relational database and Mongo is not. The FlapDoodle embedded Mongo is a replacement for H2)
- [x] Make custom events compatible with MongoDB
- [x] Refactor, remove SQL parts and annotations.
- [x] Make embedded mongo work on all architectures.
- [x] Configure for Cosmos DB

This issue is considered "done" when the application can successfully connect to the Cosmos DB on startup, and you're able to save a schedule to the database. The app should build and pass tests successfully.

**Comment by JasonFreeberg** [comment]
Whoever takes this issue, ping me when you start on it and I can provide some guidance

**Comment by Ramon-W** [comment]
I have pretty much completed this issue. However, I'm at a crossroads.

Embedded Mongo v2.2.0 works with our current version of Spring Boot v2.2.1, but for some OS architectures (like m1 mac) it requires devs to locally hardcode their architecture or else it uses an incompatible mongo version [Related thread].(https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/337). https://github.com/flapdoodle-
<img width="517" alt="Screen Shot 2023-01-27 at 8 36 00 PM" src="https://user-images.githubusercontent.com/77691280/215242214-6bdd4c86-edaa-4f86-a928-023383f9684f.png">

To avoid this, I tried using a newer Embedded Mongo v3.0.0 along with the required Spring Boot v2.5.0+. Turns out this works without needing to hardcode the architecture or change anything else in the code. However, on startup there's an ugly stack trace which seems harmless [Related thread]. This problem is likely removed with a later version of Embedded Mongo. 
<img width="759" alt="Screen Shot 2023-01-27 at 8 44 50 PM" src="https://user-images.githubusercontent.com/77691280/215242477-a66e7b68-b7cf-4f70-8535-8d2f9b709cde.png">

So I'm wondering if we might take a new approach altogether and migrate to the latest stable Spring Boot v3.0.0 (v2.7.x removed integration support for Embedded Mongo, so we'll have to use [this](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/tree/spring-3.0.x))

**Comment by Ramon-W** [comment]
@JasonFreeberg 
I've decided to stick to Embedded Mongo v2.2.0 for now to have as little changes as possible.

There's another issue we may have not been aware of though... Although CosmosDB and MongoDB are very similar functionally, they are not the same/compatible. 

One solution would be to create two versions of the same code—namely ScheduleRepository, the db config file, some tests, and ScheduleController—and differentiate them using @Profile("dev") or @Profile("prod"). 

Another would be to stick solely to either MongoDB or CosmosDB. For the former option, we could use MongoDB Atlas for production. For the latter, we could use CosmosDB Emulator for development.

Let me know what to do.

**Comment by JasonFreeberg** [comment]
Wow what a pain this has been! What are the compatibility issues you're running into with the Mongo API on Cosmos?

**Comment by Ramon-W** [comment]
Oh! I did not realize that CosmosDB could also be for MongoDB API. In that case, I think I configured things right and I'll pull request for review.
