### ISSUE TITLE
Infrastructure: create the Database

### ISSUE THREAD

**Issue by JasonFreeberg** [data-science-ucsb/gauchocourses#7]
**Background**: I originally implemented the app with Azure PostgreSQL. I had all of the infrastructure in my work account, so price was not a concern. However, price is now a concern since this will be hosted in the club account. Azure Cosmos DB is another database option which has a free tier, where the first 1000 requests and 25 GB are free.

**Tasks**:
- [ ] Create a Cosmos DB free tier: https://learn.microsoft.com/en-us/azure/cosmos-db/free-tier
- [ ] Save the access credentials/keys/password! You're going to need this later to connect the DB and application

**Comment by calee14** [comment]
While browsing the Azure services for Postgresql, I was not able to find a free tier plan for Postgres in the Cosmos DB services. I realized that the Cosmos DB free tier plan that you mentioned (1000 requests/s and 25 GB free) only applied to the NoSQL services. When I tried to use the Cosmos service to make a Postgresql database server it kept sending me to a page where I needed to create a cluster of Postgresql databases. The costs for hosting a Postgresql cluster was expensive and I don't think I was in the right direction to set up the database. I looked at the Flexible Postgresql database servers and there is a free plan that lasts only for 12 months. I'll read more into it to try to find a better free tier services, but this is what I have found so far.

Here's a page on the Cosmos DB service specifically for Postgresql databases and I could only find pricing plans to host clusters. 
https://learn.microsoft.com/en-us/azure/cosmos-db/postgresql/resources-pricing

**Comment by calee14** [comment]
Hello @JasonFreeberg, I might need some assistance setting up a Database and choosing the right plan because I having trouble finding the plan you mentioned in the post. 

I seem to be confused by the Cosmos DB plan for their PostgreSQL databases. When I try to make a Cosmos DB PostgreSQL database it sends me to a page where I am prompted to create a database cluster. From what I'm guessing, setting up a cluster would mean that we would be paying every month to keep these servers up and running to host our databases. I don't think that is what we are looking for.

I also looked into the Cosmos DB free tier plan involving the 1000 free requests but that seems to be only for the NoSQL services like MongoDB. I also viewed the other PostgreSQL database services Azure has to offer and all of them require me to purchase vCores and storage for a virtual machine to host the database. I also don't think this was what we were going for.

Jason I'm not sure what the best approach is for the database in terms of pricing. I read that the Azure PostgreSQL Flexible servers have a 12 month free tier, but that only covers one year. I'm not sure what our budget is based on our business strategy.

**Comment by JasonFreeberg** [comment]
Hi @calee14 -- The plan is to use Cosmos DB and the MongoDB API to take advantage of the free tier pricing. I mentioned PostgreSQL because that's what the backend is currently using, so we'll have to make a refactor on the backend config to use NoSQL instead. 

So you can go ahead and create the Cosmos Free tier, I'll create the backend issue for the config update.
